# Generated by Django 3.0.1 on 2019-12-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Burger')),
                ('opis', models.CharField(max_length=255, verbose_name='Opis')),
                ('rozmiar', models.CharField(choices=[('L', 'duży'), ('S', 'mały')], default='L', max_length=1)),
                ('mieso', models.CharField(choices=[('K', 'kurczak'), ('W', 'wołowina')], default='W', max_length=1)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, verbose_name='składnik')),
                ('burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skladnik', to='bar.Burger')),
            ],
        ),
    ]
