# Generated by Django 3.0.1 on 2019-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_auto_20191223_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienieobiekt',
            name='czy_zamowione',
        ),
        migrations.AddField(
            model_name='zamowienieobiekt',
            name='ilosc',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='wlasciciel',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
