# Generated by Django 3.0.1 on 2019-12-23 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bar', '0004_auto_20191223_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('ukonczone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mieso', models.CharField(max_length=255, verbose_name='mieso')),
                ('rozmiar', models.CharField(max_length=255, verbose_name='rozmiar')),
                ('ilosc', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='produkty',
        ),
        migrations.RemoveField(
            model_name='zamowienieobiekt',
            name='produkt',
        ),
        migrations.RemoveField(
            model_name='burger',
            name='mieso',
        ),
        migrations.RemoveField(
            model_name='burger',
            name='rozmiar',
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='burger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skladnik', to='bar.Burger'),
        ),
        migrations.DeleteModel(
            name='Konto',
        ),
        migrations.DeleteModel(
            name='Zamowienie',
        ),
        migrations.DeleteModel(
            name='ZamowienieObiekt',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.Burger'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='bar.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
