# Generated by Django 3.0.1 on 2019-12-24 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0007_auto_20191224_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mieso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='mieso')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rozmiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='rozmiar')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='skladnik',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='mieso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.Mieso'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='rozmiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.Rozmiar'),
        ),
    ]
