# Generated by Django 3.0.1 on 2019-12-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_auto_20191224_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladnik',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=51, max_digits=5),
        ),
    ]
