# Generated by Django 3.0.1 on 2019-12-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_auto_20191224_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='mieso',
            field=models.CharField(max_length=255, verbose_name='mieso'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='rozmiar',
            field=models.CharField(max_length=255, verbose_name='rozmiar'),
        ),
    ]
