# Generated by Django 3.0.1 on 2019-12-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0011_auto_20191224_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='mieso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.Mieso'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='rozmiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.Rozmiar'),
        ),
    ]
