# Generated by Django 3.0.1 on 2019-12-24 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bar', '0012_auto_20191224_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50, verbose_name='imie')),
                ('nazwisko', models.CharField(max_length=50, verbose_name='nazwisko')),
                ('adres', models.CharField(max_length=150, verbose_name='adres')),
                ('miasto', models.CharField(max_length=150, verbose_name='miasto')),
                ('telefon', models.IntegerField(max_length=150, verbose_name='telefon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
