# Generated by Django 3.0.1 on 2019-12-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0013_userextended'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cena_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
