# Generated by Django 3.0.1 on 2019-12-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0015_burger_obraz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='obraz',
            field=models.CharField(max_length=100, verbose_name='obraz'),
        ),
    ]
