# Generated by Django 3.0.1 on 2019-12-25 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bar', '0017_auto_20191225_0347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burger',
            options={'verbose_name_plural': 'Burgery'},
        ),
        migrations.AlterModelOptions(
            name='mieso',
            options={'verbose_name_plural': 'Mieso'},
        ),
        migrations.AlterModelOptions(
            name='rozmiar',
            options={'verbose_name_plural': 'Rozmiary'},
        ),
        migrations.AlterModelOptions(
            name='skladnik',
            options={'verbose_name_plural': 'Skladniki'},
        ),
        migrations.AlterModelOptions(
            name='userextended',
            options={'verbose_name_plural': 'Users Extended'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_time',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('ukonczone', models.BooleanField(default=False)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bar.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
