# Generated by Django 3.0.1 on 2019-12-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0018_auto_20191225_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_extended',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bar.UserExtended'),
            preserve_default=False,
        ),
    ]
